{% set data = load_setup_py_data() %}

package:
  name: photodiag
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - photodiag = photodiag.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - bokeh>=1.3
    - scipy>=0.17
    - pandas
    - h5py
    - numpy>=1.15

about:
  home: https://github.com/paulscherrerinstitute/photodiag
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
